import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.0";

// Interface for the payload coming from the Supabase Database Webhook
interface WebhookPayload {
  type: "INSERT" | "UPDATE";
  table: string;
  record: {
    id: string;
    organization_id: string;
    insumo_id: string;
    provider_id: string;
    status: string;
    quantity_requested: number;
    ai_generated: boolean;
  };
}

serve(async (req) => {
  try {
    const payload: WebhookPayload = await req.json();

    // Only process new PENDING orders generated by AI
    if (payload.type !== "INSERT" || payload.record.status !== "PENDING" || !payload.record.ai_generated) {
      return new Response(JSON.stringify({ message: "Ignored: Not a pending AI order" }), { status: 200 });
    }

    const { id, organization_id, insumo_id, provider_id, quantity_requested } = payload.record;

    // Initialize Supabase Client
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch necessary data: Provider details, Insumo details, and Organization name
    const [providerRes, insumoRes, orgRes] = await Promise.all([
      supabase.from("insumo_providers").select("*").eq("id", provider_id).single(),
      supabase.from("chakra_stock_items").select("*").eq("id", insumo_id).single(),
      supabase.from("organizations").select("name").eq("id", organization_id).single(),
    ]);

    if (providerRes.error || insumoRes.error || orgRes.error) {
      console.error("Error fetching data:", { p: providerRes.error, i: insumoRes.error, o: orgRes.error });
      throw new Error("Failed to fetch relational data");
    }

    const provider = providerRes.data;
    const insumo = insumoRes.data;
    const orgName = orgRes.data.name;

    if (!provider.phone) {
      console.warn(`Provider ${provider.name} has no phone number. Cannot auto-restock via WhatsApp.`);
      // Update order to cancelled or failed
      await supabase.from("insumo_purchase_orders").update({ status: 'CANCELLED' }).eq("id", id);
      return new Response(JSON.stringify({ message: "Provider lacks phone number" }), { status: 200 });
    }

    // Prepare WhatsApp Message Content (Meta Cloud API Template)
    // WhatsApp Cloud API requires a pre-approved template for business-initiated messages.
    // We will assume a template named "growy_restock_order" with the following variables:
    // {{1}} = Contact Name / Provider Name
    // {{2}} = Organization Name
    // {{3}} = Insumo Name
    // {{4}} = Quantity
    // {{5}} = Unit of measurement (e.g., 50L)
    
    // Clean phone number (WhatsApp API requires just digits, no plus, spaces, etc.)
    const cleanPhone = provider.phone.replace(/[\s\-\(\)\+]/g, '');
    
    // Fallback presentation string
    const presentation = `${insumo.total_volume} ${insumo.unit_of_measurement}`;
    const insumoFullName = insumo.categoria ? `${insumo.categoria} - ${insumo.nombre}` : insumo.nombre;

    // Send WhatsApp Message using Meta Cloud API (Centralized TrazAPP credentials)
    const whatsappToken = Deno.env.get("WHATSAPP_API_TOKEN");
    const whatsappPhoneId = Deno.env.get("WHATSAPP_PHONE_ID"); // the Phone Number ID from Meta App Dashboard
    
    if (!whatsappToken || !whatsappPhoneId) {
      console.error("WhatsApp environment variables (WHATSAPP_API_TOKEN, WHATSAPP_PHONE_ID) are missing.");
      throw new Error("WhatsApp provider not configured");
    }

    const whatsappRes = await fetch(`https://graph.facebook.com/v18.0/${whatsappPhoneId}/messages`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${whatsappToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messaging_product: "whatsapp",
        to: cleanPhone,
        type: "template",
        template: {
          name: "growy_restock_order",
          language: {
            code: "es_AR"
          },
          components: [
            {
              type: "header",
              parameters: [
                { type: "text", text: orgName } // Header {{1}} = Chakra
              ]
            },
            {
              type: "body",
              parameters: [
                { type: "text", text: provider.contact_name || provider.name }, // Body {{1}} = Sebastián
                { type: "text", text: orgName },                               // Body {{2}} = Chakra
                { type: "text", text: insumoFullName },                        // Body {{3}} = Sustrato Light Mix
                { type: "text", text: quantity_requested.toString() },         // Body {{4}} = 15
                { type: "text", text: presentation }                           // Body {{5}} = 80 Litros
              ]
            }
          ]
        }
      }),
    });

    if (!whatsappRes.ok) {
      const errorText = await whatsappRes.text();
      console.error("Error from WhatsApp Meta API:", errorText);
      throw new Error("Failed to send WhatsApp message");
    }

    // Mark the order as SENT
    await supabase.from("insumo_purchase_orders").update({ status: 'SENT' }).eq("id", id);

    return new Response(JSON.stringify({ 
      success: true, 
      message: `Restock WhatsApp sent to ${cleanPhone}` 
    }), { 
      status: 200,
      headers: { "Content-Type": "application/json" }
    });

  } catch (err: any) {
    console.error("Function error:", err.message);
    return new Response(JSON.stringify({ error: err.message }), { 
      status: 500,
      headers: { "Content-Type": "application/json" }
    });
  }
});
